### PR TITLE
Projects when created must have a name

### PR DESCRIPTION
**Pull request by trycatcher**
Project creation with an empty/blank name is no longer possible. Showing a corresponding message on screen when that is attempted.

### CODE REVIEW

**Comment by jysandy** [comment]
@trycatcher I will merge this along with https://github.com/nilenso/time-tracker/pull/73

**Comment by jysandy** [comment]
Please fix the merge conflicts.

**Review by jysandy — CHANGES_REQUESTED** [review]
Please fix the merge conflicts.

**Comment by trycatcher** [comment]
@jysandy Fixed the merge conflicts. Should be safe to merge now.

**Review by jysandy — APPROVED** [review]

**Pull request merged**
