### PR TITLE
Removing button to change date and doing the same on input entry

### PR DESCRIPTION
**Pull request by trycatcher**
This makes sure that user-provided dates are used for invoice generation

### CODE REVIEW

**Comment by jysandy** [comment]
Good fix...this component was quite broken.

**Review by jysandy — APPROVED** [review]

**Comment by jysandy** [comment]
@trycatcher is this the corresponding issue for this PR? Please confirm before I merge. https://github.com/nilenso/time-tracker/issues/80

**Comment by jysandy** [comment]
This change in itself is fine. JFYI though, a better way to architect this component would be to remove its local state entirely. Many components in the current frontend share this issue (they have local state when they really shouldn't need it).

**Comment by jysandy** [comment]
Also I disabled CI for this. I don't know how CI was enabled in the first place.

**Comment by trycatcher** [comment]
@jysandy Yes, this is the fix for https://github.com/nilenso/time-tracker/issues/80

**Pull request merged**
